eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/

server:
  port: 10012

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.119.96.130/chee?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    password: Qq123456&
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000

mybatis:
  typeAliasesPackage: com.cloud.user.dao
  mapperLocations: classpath:mapper/**/*.xml

app:
  appSecret: xJ2v6j3YQA6JqaHuMKoclA
  sms:
    miaodi:
      url: https://api.miaodiyun.com/20150822/industrySMS/sendSMS?accountSid={accountSid}&to={to}&smsContent={smsContent}&timestamp={timestamp}&sig={sig}
      token:  b7f9f95b67f14d0fbb61ad009da32b41
      accountSid: 4b89b5663dee49649c77c35c51856585
      smsContent: 【易科技】您的验证码为{code}，请于3分钟内正确输入，如非本人操作，请忽略此短信。

logging:
  path: /data/logs/cloud-user
  level:
    com.cloud.user: INFO
    org.springframework.web: DEBUG