eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:20001/eureka/
            
server:
  port: 10011
  
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.119.96.130/chee?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    password: Qq123456&
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000
      
mybatis:
  typeAliasesPackage: com.cloud.schedule.dao
  mapperLocations: classpath:mapper/**/*.xml
  
app:
  appSecret: xJ2v6j3YQA6JqaHuMKoclA
  
logging:
  path: /data/logs/cloud-schedule
  level:
    com.cloud.schedule: INFO
    org.springframework.web: DEBUG
